version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: scheele/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: georgesamir21/udagram-api-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: georgesamir21/udagram-api-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: geogeorgesamir21/udagram-front-end
